### ✅ 1. Crear curso válido
POST http://localhost:9090/api/cursos
Authorization: Basic profe:admin
Content-Type: application/json

{
  "nombre": "INGENIERIA DEL SOFTWARE",
  "profesor": "Nacho"
}


### ✅ 5. Actualizar curso
PUT http://localhost:9090/api/cursos/1
Authorization: Basic profe:admin
Content-Type: application/json
Accept: application/json

{
  "nombre": "Matemáticas Avanzadas",
  "profesor": "Ana López"
}


### ✅ 6. Eliminar curso
DELETE http://localhost:9090/api/cursos/1
Authorization: Basic profe:admin
Accept: application/json


### ✅ 7. Crear curso para probar alumnos
POST http://localhost:9090/api/cursos
Authorization: Basic profe:admin
Content-Type: application/json
Accept: application/json

{
  "nombre": "Física",
  "profesor": "Laura Sánchez"
}


### ✅ 8. Crear alumno válido
POST http://localhost:9090/api/alumnos
Authorization: Basic profe:admin
Content-Type: application/json
Accept: application/json

{
  "nombre": "Diego",
  "email": "lucia.gomez@example.com",
  "cursoId": 2
}


### ✅ 13. Actualizar alumno
PUT http://localhost:9090/api/alumnos/3
Authorization: Basic profe:admin
Content-Type: application/json
Accept: application/json

{
  "nombre": "Raquel Gómez Ramírez",
  "email": "raquel.ramirez@example.com",
  "cursoId": 2
}


### ✅ 14. Eliminar alumno
DELETE http://localhost:9090/api/alumnos/1
Authorization: Basic profe:admin
Accept: application/json


### ✅ Creación de alumno simple (ejemplo admin permitido)
POST http://localhost:8080/api/alumnos
Authorization: Basic profe:admin
Content-Type: application/json

{
  "nombre": "Ana"
}


### ✅ Acceso a endpoint solo para ADMIN
GET http://localhost:8080/api/admin/secret
Authorization: Basic profe:admin


### ✅ Lectura pública protegida (alumno)
GET http://localhost:8080/api/hola
Authorization: Basic alumno:1234


### ✅ Lectura de todos los alumnos (alumno)
GET http://localhost:8080/api/alumnos
Authorization: Basic alumno:1234


### ❌ Intento de creación de alumno (POST) — Prohibido para USER (alumno)
POST http://localhost:8080/api/alumnos
Authorization: Basic alumno:1234
Content-Type: application/json

{
  "nombre": "Ana"
}


### ❌ Acceso sin credenciales (debe fallar con 401 Unauthorized)
GET http://localhost:8081/api/hola
